//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemanHP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailPembelian
    {
        public int Id { get; set; }
        public int PembelianId { get; set; }
        public int BarangId { get; set; }
        public double Discount { get; set; }
        public double Harga { get; set; }
        public double Jumlah { get; set; }

        public virtual Pembelian Pembelian { get; set; }
        public virtual Barang Barang { get; set; }
    }
}
