//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemanHP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelanggan
    {
        public Pelanggan()
        {
            this.Pembelians = new HashSet<Pembelian>();
        }
    
        public int Id { get; set; }
        public string Nama { get; set; }
        public string Email { get; set; }
        public string Telepon { get; set; }
        public string Alamat { get; set; }
        public DateTime TanggalDaftar { get; set; }
        public string UserId { get; set; }
        public string KodeKota { get; set; }
        public virtual ICollection<Pembelian> Pembelians { get; set; }
        public string Password { get; internal set; }
    }
}
