//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemanHP.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System;
    using System.Collections.Generic;
    
    public partial class Pembelian
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pembelian()
        {
            this.DetailPembelians = new HashSet<DetailPembelian>();
        }

        public int Id { get; set; }
        public int PelangganId { get; set; }
        public double KodeValidasiPembayaran { get; set; }
        public System.DateTime Tanggal { get; set; }
        [JsonConverter(typeof(StringEnumConverter))]
        public StatusPembelian StatusPembelian { get; set; }
        public string KodePemesanan { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailPembelian> DetailPembelians { get; set; }
        public virtual Pembayaran Pembayaran { get; set; }
        public virtual Pengiriman Pengiriman { get; set; }
    }
}
