//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemanHP.Models
{
    using System.Linq;


    public partial class Produk : Barang
    {
        private byte[] gambar;

        public int JenisProdukId { get; set; }
        public string Warna { get; set; }
        public string Dimensi { get; set; }
        public string Size { get; set; }

        public virtual JenisProduk JenisProduk { get; set; }


        public byte[] Gambar
        {
            get
            {
                if (gambar == null)
                {
                    if (Fotoes != null && Fotoes.Count > 0)
                    {
                        gambar = Fotoes.FirstOrDefault().Picture;
                    }
                }
                return gambar;

            }
            set { SetProperty(ref gambar, value); }
        }

    }
}
